package runtime

import (
	"log/slog"
	"sort"
	"testing"

	"github.com/matutetandil/mycel/v2/internal/connector"
	"github.com/matutetandil/mycel/v2/pkg/schema"
)

// The three lists that have to agree about which connectors exist.
//
// A connector type is named in three places: the factories the runtime
// registers (what can be built), the schema registry (what completions,
// `mycel add` and validation know about), and the parser's list of built-in
// types (which decides whether an unknown attribute is a typo or a plugin's
// own setting). Nothing compared them.
//
// Each disagreement has a distinct failure. A type with a factory and no
// schema is a connector that runs and cannot be completed or validated. A type
// in the parser's list with no factory is a configuration that parses cleanly
// and then fails to start with "no factory found". A schema with no factory is
// a connector the documentation and `mycel add` offer and nothing can build —
// the shape this project has hit repeatedly, most recently as a root block
// that had a schema, a test asserting it existed, and no parser behind it.

// buildable reports whether anything can build this type, trying each driver
// the type's schema declares. A type whose driver is required cannot be built
// without one, and that is the correct answer rather than a gap.
func buildable(registry *connector.Registry, reg *schema.Registry, connType string) bool {
	if registry.Supports(connType, "") {
		return true
	}
	block := reg.ConnectorSchema(connType, "")
	for _, attr := range block.Attrs {
		if attr.Name != "driver" {
			continue
		}
		for _, driver := range attr.Values {
			if registry.Supports(connType, driver) {
				return true
			}
		}
	}
	return false
}

func TestEveryConnectorTheRuntimeCanBuildHasASchema(t *testing.T) {
	// Without one, a connector runs but cannot be completed, generated by
	// `mycel add`, or checked by `mycel validate` — which since 2.12.0 is what
	// enforces the attributes a from block requires.
	registry := connector.NewRegistry()
	registerBuiltinFactories(registry, slog.Default())
	schemaReg := NewSchemaRegistry()

	var missing []string
	for _, connType := range schema.ConnectorTypeNames() {
		if !buildable(registry, schemaReg, connType) {
			continue
		}
		if schemaReg.Lookup(connType, "") == nil {
			missing = append(missing, connType)
		}
	}
	sort.Strings(missing)

	if len(missing) > 0 {
		t.Errorf("these connectors can be built and describe nothing about themselves: %v", missing)
	}
}

func TestEveryConnectorWithASchemaCanBeBuilt(t *testing.T) {
	// The other direction, and the more embarrassing one: a connector offered
	// by completions and `mycel add` that fails at start-up with "no factory
	// found for connector type".
	registry := connector.NewRegistry()
	registerBuiltinFactories(registry, slog.Default())

	schemaReg := NewSchemaRegistry()

	var unbuildable []string
	for _, connType := range schemaReg.AllConnectorTypes() {
		if !buildable(registry, schemaReg, connType) {
			unbuildable = append(unbuildable, connType)
		}
	}
	sort.Strings(unbuildable)

	if len(unbuildable) > 0 {
		t.Errorf("these connectors are described but nothing can build them: %v", unbuildable)
	}
}

func TestTheParsersListOfBuiltInTypesIsTheRuntimes(t *testing.T) {
	// This list decides how strictly a connector block is checked: a type on
	// it is held to the attributes that exist, and one that is not carries
	// whatever a plugin declared. A type missing from it means a real
	// connector's typos are accepted silently; a type on it that the runtime
	// cannot build means a configuration that parses and will not start.
	registry := connector.NewRegistry()
	registerBuiltinFactories(registry, slog.Default())

	schemaReg := NewSchemaRegistry()

	var unbuildable []string
	for _, connType := range schema.ConnectorTypeNames() {
		if !buildable(registry, schemaReg, connType) {
			unbuildable = append(unbuildable, connType)
		}
	}
	sort.Strings(unbuildable)

	if len(unbuildable) > 0 {
		t.Errorf("the parser treats these as built-in and nothing builds them: %v", unbuildable)
	}
}

func TestEachDatabaseAndQueueDriverIsBuildable(t *testing.T) {
	// The driver is what picks the implementation inside a type, so a driver
	// named in a schema and unknown to every factory is a configuration that
	// completes, validates, and fails at start-up.
	registry := connector.NewRegistry()
	registerBuiltinFactories(registry, slog.Default())

	for _, tc := range []struct{ connType, driver string }{
		{"database", "postgres"},
		{"database", "mysql"},
		{"database", "sqlite"},
		{"database", "mongodb"},
		{"mq", "rabbitmq"},
		{"mq", "kafka"},
		{"mq", "redis"},
		{"cache", "memory"},
		{"cache", "redis"},
	} {
		if !registry.Supports(tc.connType, tc.driver) {
			t.Errorf("nothing builds a %s connector with driver %q", tc.connType, tc.driver)
		}
	}

	// And a driver nobody implements is refused rather than quietly built as
	// something else.
	if registry.Supports("database", "oracle") {
		t.Error("a database driver nobody implements was accepted")
	}
}
