{{- if .Values.mycel.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mycel.secretName" . }}
  labels:
    {{- include "mycel.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.mycel.secrets.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
